Search page
HEHOHADA/git-clone-ts-gql pull request #7
Opened 2020-11-01 10:53 UTC by aidagalimova

2020-11-01 12:36 UTC, HEHOHADA requested changes
Смержи лучше с девом вначале
а то у тебя те же изменения, что и с прошлым коммитом

2020-11-01 13:06 UTC, HEHOHADA commented on src/components/Search/RepositorySearchResult.tsx
> +          name: "Repository2",
лучше замоковать како-нибудь
если это будет компонент представления в него должны входить набор пропсов, а не 1 поле

2020-11-01 13:06 UTC, HEHOHADA commented on src/components/User/ShortUser.tsx
> +      <Link href={user.url} className={classes.link}>
почему линк из material, а не react?

2020-11-01 13:06 UTC, HEHOHADA commented on src/components/User/ShortUser.tsx
> +  user.avatar = AvatarEx;
???

2020-11-01 13:06 UTC, HEHOHADA commented on src/pages/Search.tsx
> +export default function Login() {
Логин?

2020-11-01 13:06 UTC, HEHOHADA commented on src/components/Search/Search.tsx
> +  const [searchType, setType] = React.useState("repositories");
Таки более красивее испортировать useState from 'react'

2020-11-01 13:06 UTC, HEHOHADA commented on src/components/Search/Search.tsx
> +          <UserSearchResult input={userInput} />
Что это

2020-11-03 12:31 UTC, aidagalimova commented on src/components/Search/Search.tsx
> +          <UserSearchResult input={userInput} />
для поиска по репозиториям или по юзерам

2020-11-03 12:31 UTC, aidagalimova commented on src/components/Search/RepositorySearchResult.tsx
> +          name: "Repository2",
я не поняла...

2020-11-03 12:42 UTC, HEHOHADA commented on src/components/Search/RepositorySearchResult.tsx
> +          name: "Repository2",
Есть компоненты представления, есть компоненты с данными
а это как бы компонент представлнения, а как бы и нет

2020-11-03 12:43 UTC, HEHOHADA commented on src/components/Search/Search.tsx
> +          <UserSearchResult input={userInput} />
и почему в  репозиторий идет userInput?

2020-11-03 12:47 UTC, HEHOHADA commented
называй свои коммиты как-нибудь понятнее, чем фиксес

2020-11-03 12:50 UTC, aidagalimova commented on src/components/Search/Search.tsx
> +          <UserSearchResult input={userInput} />
userinput это то что пользователь вводит

2020-11-03 13:40 UTC, HEHOHADA commented on src/components/Search/Search.tsx
> +  const [searchType, setType] = React.useState("repositories");
И тогда напиши тип всех возможный SearchType

2020-11-03 13:40 UTC, HEHOHADA commented on src/components/Search/Search.tsx
> +          <UserSearchResult input={userInput} />
Назови по-другому, что-то более понятнее

2020-11-03 14:00 UTC, HEHOHADA commented on src/components/Repository/ShortRepository.tsx
> +const ShortRepository = ({ repository }: { repository: any }) => {
Старайся для каждого компонента писать FC<PropsType>
Где PropsType тип пропсов

2020-11-03 14:00 UTC, HEHOHADA commented on src/components/Repository/ShortRepository.tsx
> +          <StarIcon style={{ color: 'white' }} />
У тебя же они одинаковые

2020-11-05 13:38 UTC, aidagalimova commented on src/components/Search/Search.tsx
> +  const [searchType, setType] = React.useState("repositories");
'users' и 'repositories' вынести в переменную?

2020-11-05 13:54 UTC, HEHOHADA commented on src/components/Search/Search.tsx
> +  const [searchType, setType] = React.useState("repositories");
type SearchType = 'users' | 'repositories'
https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html

2020-11-05 15:07 UTC, HEHOHADA commented on src/models/user.tsx
> +export interface User {
Нуу это не шарп 
создай скорее types и оттуда экспортируй все

2020-11-05 15:07 UTC, HEHOHADA commented on src/components/Repository/ShortRepository.tsx
> +}
А зачем экспортировать?
если нигде не используется создавай локальные

2020-11-05 15:07 UTC, HEHOHADA commented on src/components/Search/Search.tsx
> +  type searchType = 'repositories' | 'users'
называй типы все-таки с большой
и лучше вынеси ее куда-нибудь
она ж не только тут будет использоваться

2020-11-05 15:07 UTC, HEHOHADA commented on src/components/Search/UserSearchResult.tsx
>    </div>
а как инпут вообще используется
и ты уверена, что users будет храниться в переменной, а не прокидываться через пропсы?
также в кмопоненте с repos

2020-11-05 15:17 UTC, aidagalimova commented on src/components/Search/UserSearchResult.tsx
>    </div>
ну да, щас никак, инпут должен отправляться в запросе, который должен вернуть users

2020-11-05 15:18 UTC, aidagalimova commented on src/components/Search/Search.tsx
> +  type searchType = 'repositories' | 'users'
хм, а где еще кроме поиска?

2020-11-05 15:21 UTC, HEHOHADA commented on src/components/Search/Search.tsx
> +  type searchType = 'repositories' | 'users'
где-нибудь 
кто ж знает
есть у нас будет старница поиска
и поиск в навбаре
к тому же я имел в виду использовать тип как 
useState<SearchType>

2020-11-05 15:25 UTC, aidagalimova commented on src/models/user.tsx
> +export interface User {
папку тайпс?

2020-11-05 15:28 UTC, HEHOHADA commented on src/models/user.tsx
> +export interface User {
Да

2020-11-05 17:17 UTC, HEHOHADA commented on src/components/Repository/Repositories.tsx
> +    </div>
У каждого элемента, который проходит через map
Должен быть key, чтобы react мог оптимизировать его рендер

2020-11-05 17:17 UTC, HEHOHADA commented on src/components/Repository/ShortRepository.tsx
> +        )}
а почему внутри нельзя стиль задать?

2020-11-05 17:17 UTC, HEHOHADA commented on src/types/repository.tsx
> +  ownerLogin: string
tsx?

2020-11-05 18:14 UTC, HEHOHADA commented on src/components/Repository/ShortRepository.tsx
>          )}
<StarIcon className={isStarred? classes.starred:classes,NotStarred}/>?

2020-11-05 18:16 UTC, HEHOHADA commented on src/components/Repository/ShortRepository.tsx
> +        )}
<StarIcon className={isStarred? classes.starred:classes,NotStarred}/>?

2020-11-05 19:01 UTC, HEHOHADA approved these changes

2020-11-05 19:01 UTC, merged